# -*- coding: utf-8 -*-
"""ArtImagesClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9dSl8zB_Hrt0QhDAYpJTM1EdswhlZQv
"""

# !git clone https://github.com/Billy-06/ArtClassification.git

# Commented out IPython magic to ensure Python compatibility.
# %cd ArtClassification/application/data/

# %cd ../../../../
# !rm -rf ArtClassification

# !ls

# !git clone https://github.com/ultralytics/yolov5.git

# !ls

# # Commented out IPython magic to ensure Python compatibility.
# !ls
# %cd yolov5

# !pip install -r requirements.txt

# !python train.py --img 1024 --batch-size 24 --epochs 10 --data arts_classification.yaml --freeze 0 1 2 3 4 5 --weights yolov5s.pt --workers=0

# !ls

# !rm -rf runs

import shutil
shutil.make_archive('runs', 'zip', 'runs')

